version: '3'

services:
  rdb.api:
    image: rdb.api
    build:
      context: ./RDB.Api
      dockerfile: Dockerfile
    links:
      - mongo
  rdb.admin:
    image: rdb.admin
    build:
      context: ./RDB.Admin
      dockerfile: Dockerfile
    links:
      - rdb.api
  mongo:
    image: mongo
    volumes:
      - data:/data/db
  lb:
    image: dockercloud/haproxy
    links:
      - rdb.api
      - rdb.admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
