version: '3'

services:
  rdb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18420:80"

  rdb.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18421:80"
