version: '3'

services:
  api:
    environment:
      - ASPNETCORE_URLS=http://*:80
      - VIRTUAL_HOST=*:80/api*
      - VIRTUAL_HOST_WEIGHT=1
    ports:
      - "80"
  admin:
    environment:
      - ASPNETCORE_URLS=http://*:80
      - VIRTUAL_HOST=*:80
      - App:ApiUrl=http://rdb.northeurope.cloudapp.azure.com/api/
    ports:
      - "80"
  lb:
    ports:
      - "80:80"
      - "1936:1936"
