version: '3'

services:
  rdb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
  mongo:
    ports:
      - "18427:27017"
    volumes:
      - data:/data

volumes:
  data: