version: '3'

services:
  rdb.api:
    image: rdb.api
    build:
      context: ./RDB.Api
      dockerfile: Dockerfile
    links:
      - mongo
  rdb.admin:
    image: rdb.admin
    build:
      context: ./RDB.Admin
      dockerfile: Dockerfile
  mongo:
    image: mongo