version: '3'

services:
  rdb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18420:80"
  rdb.admin:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "18421:5000"
    volumes:
      - ./RDB.Admin:/app
      - /app/bin
      - /app/obj
      - ~/.nuget/packages:/root/.nuget/packages
      - /root/.nuget/packages/.tools

volumes:
  data:
