version: '3'

services:
  rdb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "18420:80"
  rdb.admin:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "18421:80"
    volumes:
      - ./RDB.Admin:/app
      - /app/obj
      - /app/bin
  mongo:
    ports:
      - "18427:27017"
    volumes:
      - data:/data/db

volumes:
  data: