version: '3'

services:
  api:
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - VIRTUAL_HOST=*:8080/api*
      - VIRTUAL_HOST_WEIGHT=1
    ports:
      - "8080"
  admin:
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - VIRTUAL_HOST=*:8080
    ports:
      - "8080"
  lb:
    ports:
      - "8080:8080"
      - "1936:1936"
