version: '3'

services:
  api:
    build:
      context: ./RDB.Api
      dockerfile: Dockerfile
    links:
      - mongo
  admin:
    build:
      context: ./RDB.Admin
      dockerfile: Dockerfile
    links:
      - api
  mongo:
    image: mongo
    volumes:
      - data:/data/db
  lb:
    image: dockercloud/haproxy
    links:
      - api
      - admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
