version: '3'

services:
  rdb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - VIRTUAL_HOST=*:8080/api/*
      - VIRTUAL_HOST_WEIGHT=1
    ports:
      - "8080"
  rdb.admin:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - VIRTUAL_HOST=*:8080
    ports:
      - "8080"
    volumes:
      - ./RDB.Admin:/app
      - /app/bin
      - /app/obj
      - /app/node_modules
  lb:
    ports:
      - "8080:8080"
      - "1936:1936"
