// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RDB.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a text value with ID.
    /// </summary>
    public partial class Value
    {
        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        /// <param name="id">Value ID.</param>
        /// <param name="text">Value text.</param>
        public Value(string id = default(string), string text = default(string))
        {
            Id = id;
            Text = text;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets value ID.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets value text.
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

    }
}
