/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const Value = {
  required: false,
  serializedName: 'Value',
  type: {
    name: 'Composite',
    className: 'Value',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      text: {
        required: false,
        serializedName: 'text',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const RdbApiValuesPostOptionalParams = {
  required: false,
  serializedName: 'ValuesPostOptions',
  type: {
    name: 'Composite',
    className: 'RdbApiValuesPostOptionalParams',
    modelProperties: {
      text: {
        required: false,
        serializedName: 'text',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const RdbApiValuesByIdPutOptionalParams = {
  required: false,
  serializedName: 'ValuesByIdPutOptions',
  type: {
    name: 'Composite',
    className: 'RdbApiValuesByIdPutOptionalParams',
    modelProperties: {
      text: {
        required: false,
        serializedName: 'text',
        type: {
          name: 'String'
        }
      }
    }
  }
};
