#!/bin/sh
if [ "$1" = "--production" ]; then
  docker-compose -f ../docker-compose.yml -f ../docker-compose.production.yml up -d --no-deps --build admin
elif [ "$1" = "--azure" ]; then
  docker-compose -f ../docker-compose.yml -f ../docker-compose.azure.yml up -d --no-deps --build admin
elif [ "$1" = "--debug" ]; then
  export DOCKERFILE_EXT=.debug
  docker-compose up -d --no-deps --build admin
else
  docker-compose up -d --no-deps --build admin
fi
