FROM microsoft/aspnetcore-build:2.0.0-preview2 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/bin

ENTRYPOINT ["dotnet", "bin/RDB.Admin.dll"]
