FROM microsoft/aspnetcore-build:2.0.0 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm config set @creuna:registry https://www.myget.org/F/creuna/npm/ \
  && npm install
COPY *.csproj .
RUN dotnet restore
COPY . .
ENV ASPNETCORE_ENVIRONMENT=Development
RUN dotnet publish -c Release -o /app/bin --no-restore

ENTRYPOINT ["dotnet", "bin/RDB.Admin.dll"]
