FROM microsoft/aspnetcore-build:2.0.0 AS builder
RUN apt-get update \
  && apt-get install unzip \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY *.csproj .
RUN dotnet restore
COPY . .
ENV ASPNETCORE_ENVIRONMENT=Development
RUN dotnet publish -c Debug -o /app/bin --no-restore

ENTRYPOINT ["tail", "-f", "/dev/null"]
